"""Did the artifacts on disk come from `evaluate QUICK=1`?

One definition, imported by every guard that compares a *documented* figure against a
*generated* one. It lived as a private function inside
`test_results_are_reproducible.py`, which is why the second such guard was written
without it — POSTMORTEM D43.

QUICK mode is smaller batches on the same code path, and `run_evaluation` prints in its
own banner that the numbers will differ from the full run. The README and the cards quote
the **full** run, so checking either against quick artifacts compares two things that are
not supposed to agree.

CI's N4 job runs `evaluate QUICK=1` twice and then runs `tests/statistical` with
`ANTAR_REQUIRE_ARTIFACTS=1`, so this is a state every guard in this directory must expect.
Provenance is meaningful only against a full run. Internal consistency, magnitude, and
anything checking a *shape* rather than a *value* hold at any scale and keep running.
"""

from __future__ import annotations

import json

import pytest

from antar.config import artifacts_dir


def artifacts_are_from_a_quick_run() -> bool:
    marker = artifacts_dir() / "evaluation.json"
    if not marker.exists():
        return False
    try:
        return bool(json.loads(marker.read_text(encoding="utf-8")).get("quick"))
    except json.JSONDecodeError:
        return False


def requires_full_run(what: str) -> None:
    """Skip, with a reason that names what was being compared and why it cannot be.

    Call this from any check that compares a figure written into a document against a
    figure generated by the evaluation. Not from checks on shape, count, or wording -
    those are true at any batch size and should keep running on N4, or the job degrades
    into one that passes by finding nothing to look at (D28).
    """
    if artifacts_are_from_a_quick_run():
        pytest.skip(
            f"artifacts came from `evaluate QUICK=1`, whose numbers differ from the "
            f"full run {what} quotes. Values are checked against a full run; shape and "
            "wording checks still run here."
        )
