"""The operator console. Three views, as PLAN.md M9 specifies.

    python tasks.py console

> Console: three views — batch overview, decision trace explorer, shadow-price panel.
>
> **Acceptance:** Console answers *"why did you contact this customer at 11:04 on a
> Tuesday?"* in one click with a complete trace.

## Everything on screen comes from an artifact or the ledger

There is no computation in this file beyond formatting. The batch overview reads
`artifacts/batch_*.json`, the trace explorer reads the hash-chained ledger through
`audit/trace.py`, and the shadow-price panel reads `artifacts/allocation_*.json`.

That is not laziness. A console that recomputes is a second implementation of the
decision path, and when the two disagree the operator has no way to know which one is
lying. This one can only show what was recorded, which means a screenshot of it is
evidence.

## The verification banner is not decoration

Every view checks `verify_chain()` and says so at the top. A trace from a ledger that
does not verify is worse than no trace, so the console refuses to look authoritative
about one.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import streamlit as st

from antar.audit.ledger import Ledger
from antar.audit.trace import TraceIndex
from antar.config import artifacts_dir

st.set_page_config(page_title="Antar console", layout="wide")


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------


def available_ledgers() -> list[Path]:
    return sorted(artifacts_dir().glob("batch_*.db"))


@st.cache_resource
def open_ledger(path: str) -> Ledger:
    return Ledger(path)


def load_artifact(name: str) -> dict[str, Any] | None:
    path = artifacts_dir() / name
    if not path.exists():
        return None
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return None


def rupees(paise: Any) -> str:
    try:
        return f"Rs {float(paise) / 100:,.2f}"
    except (TypeError, ValueError):
        return "n/a"


def simulated_banner() -> None:
    """N6, on every screen. A number on a dashboard travels further than its caveat."""
    st.caption(
        "Every figure here is **simulated** - generated by the model described in "
        "`docs/SIMULATOR_CARD.md`, calibrated against published Indian "
        "recurring-payments figures. None of it is a measured recovery rate from a live "
        "merchant."
    )


def chain_banner(ledger: Ledger) -> bool:
    result = ledger.verify_chain()
    if result.ok:
        st.success(
            f"Ledger verifies: {result.entries_checked} entries, "
            f"head `{ledger.head()[:24]}...`"
        )
        return True
    st.error(
        f"**The ledger does not verify.** {len(result.breaks)} chain break(s), "
        f"first at seq {result.first_break.seq}: {result.first_break.detail} "
        "Treat everything below as unreliable."
    )
    return False


# ---------------------------------------------------------------------------
# View 1 - batch overview
# ---------------------------------------------------------------------------


def view_batch_overview(ledger: Ledger, scenario: str) -> None:
    st.header("Batch overview")
    simulated_banner()
    chain_banner(ledger)

    summary = load_artifact(f"batch_{scenario}.json")
    if summary is None:
        st.warning(
            f"`artifacts/batch_{scenario}.json` is missing. Run "
            f"`python tasks.py simulate SCENARIO={scenario}`."
        )
        return

    columns = st.columns(5)
    columns[0].metric("At-risk events", summary["events"])
    columns[1].metric("Contacted", summary["contacted"])
    columns[2].metric("Abstained", summary["abstained"])
    columns[3].metric("Holdout", summary["control"])
    columns[4].metric("Refused by gate", summary["refused"])

    st.markdown(
        "**Abstention is the product.** A recovery system that contacts everyone is a "
        "spam cannon with a dashboard; the interesting number above is the second-"
        "largest one."
    )

    columns = st.columns(4)
    columns[0].metric("Simulated recoveries", summary["recovered"])
    columns[1].metric("Opt-outs induced", summary["optouts"])
    columns[2].metric("Recovered", f"Rs {summary['recovered_rupees']:,.0f}")
    columns[3].metric("Net of cost", f"Rs {summary['net_rupees']:,.0f}")

    st.subheader("Provenance")
    left, right = st.columns(2)
    left.write(
        {
            "uplift model": summary["model_version"],
            "policy version": summary["policy_version"],
            "seed": summary["seed"],
        }
    )
    right.write(
        {
            "ledger entries": summary["ledger_entries"],
            "chain verified": summary.get("chain_verified"),
            "replay self-consistent": summary.get("replay_self_consistent"),
            "ledger head": summary["ledger_head"][:32] + "...",
        }
    )
    if summary.get("notes"):
        st.info("\n\n".join(summary["notes"]))

    st.subheader("Where the events went")
    kinds: dict[str, int] = {}
    for entry in ledger.entries():
        kinds[entry.kind.value] = kinds.get(entry.kind.value, 0) + 1
    st.bar_chart(kinds)


# ---------------------------------------------------------------------------
# View 2 - decision trace explorer
# ---------------------------------------------------------------------------


def view_trace_explorer(ledger: Ledger) -> None:
    st.header("Why did you contact this customer?")
    simulated_banner()
    verified = chain_banner(ledger)

    index = TraceIndex(ledger)
    event_ids = index.event_ids()
    if not event_ids:
        st.warning("This ledger has no events.")
        return

    filter_choice = st.radio(
        "Show",
        ["Contacted", "Abstained", "Holdout", "Refused", "All"],
        horizontal=True,
        index=0,
    )

    # One pass over the ledger for the whole batch, not one per event (D26).
    traces = {eid: index.trace(eid) for eid in event_ids}

    def matches(trace: Any) -> bool:
        decision = trace.decision or {}
        if filter_choice == "Contacted":
            return trace.approved
        if filter_choice == "Refused":
            return bool(trace.refusals)
        if filter_choice == "Holdout":
            return bool(decision.get("is_control"))
        if filter_choice == "Abstained":
            return not trace.actions and not decision.get("is_control")
        return True

    candidates = [eid for eid in event_ids if matches(traces[eid])]
    if not candidates:
        st.info(f"No events in this batch are **{filter_choice.lower()}**.")
        return

    event_id = st.selectbox(f"{len(candidates)} event(s)", candidates)
    trace = traces[event_id]

    st.subheader("The answer, in one paragraph")
    st.write(trace.narrate())
    if not verified:
        st.warning(
            "The narrative above is assembled from a ledger that does not verify. It "
            "is what the file says, not what necessarily happened."
        )

    st.subheader("The evidence it was assembled from")
    left, right = st.columns(2)

    with left:
        st.markdown("**Event (L1)**")
        st.json(trace.event or {"missing": True})
        st.markdown("**Diagnosis (L2)**")
        st.json(trace.diagnosis or {"missing": True})

    with right:
        st.markdown("**Decision (L3)**")
        st.json(trace.decision or {"missing": True})
        st.markdown("**Actions (L4)**")
        st.json(list(trace.actions) or {"missing": True})
        st.markdown("**Outcome**")
        st.json(trace.outcome or {"missing": True})

    st.subheader("Reproducibility")
    st.write(trace.versions or {"note": "no versions recorded"})

    money = trace.money
    columns = st.columns(4)
    columns[0].metric("Amount at risk", rupees(money["amount_paise"]))
    columns[1].metric("Expected incremental", rupees(money["expected_incremental_paise"]))
    columns[2].metric("Cost incurred", rupees(money["cost_paise"] + money["discount_paise"]))
    columns[3].metric("Recovered", rupees(money["recovered_paise"]))

    if trace.gaps:
        st.info(
            "No ledger entry exists for: " + ", ".join(trace.gaps) + ". That is "
            "reported rather than inferred - most events legitimately end at "
            "'no action was worth taking'."
        )

    with st.expander("Raw ledger entries for this event"):
        st.json([entry.model_dump(mode="json") for entry in trace.entries])


# ---------------------------------------------------------------------------
# View 3 - shadow prices
# ---------------------------------------------------------------------------


def view_shadow_prices(scenario: str) -> None:
    st.header("What each constraint costs")
    simulated_banner()

    data = load_artifact(f"allocation_{scenario}.json")
    if data is None:
        st.warning(
            f"`artifacts/allocation_{scenario}.json` is missing. Run "
            f"`python tasks.py evaluate`."
        )
        return

    st.subheader("Three policies, one contact capacity")
    st.dataframe(data["policies"], use_container_width=True)

    delta = data["antar_minus_propensity_per_1000_rupees"]
    st.metric("Antar minus propensity targeting, per 1,000 at-risk cycles", f"Rs {delta:,.0f}")
    st.caption(
        "Propensity targeting is the comparison that matters. Beating 'contact "
        "everyone' is easy and proves nothing."
    )

    prices = data.get("shadow_prices") or {}
    duals = prices.get("lp_duals") or []
    counterfactuals = prices.get("counterfactual_prices") or []
    slack = prices.get("slack_rows") or []

    st.subheader("Constraint prices")
    if duals or counterfactuals:
        st.dataframe([*duals, *counterfactuals], use_container_width=True)
    else:
        st.info("No priced constraints in this artifact.")

    if slack:
        st.info(
            f"**Non-binding rows: {', '.join(slack)}.** A zero price on contact "
            "capacity is a finding, not a null result. At this scenario's opt-out "
            "sensitivity the scarce resource is customer tolerance, not outbound "
            "capacity - Antar declines slots it is entitled to use, so one more slot "
            "is worth nothing. See `docs/LIMITATIONS.md` L14."
        )

    if prices.get("framing"):
        st.markdown(f"> {prices['framing']}")

    verdicts = data.get("retention") or []
    if verdicts:
        st.subheader("Component retention")
        st.caption(
            "The rule was pre-registered in `docs/EVALUATION.md` 12.2 before the "
            "allocator existed, and ambiguity resolves to DELETE. Both components below "
            "were deleted on it."
        )
        for row in verdicts:
            st.markdown(
                f"**{row['component']}** - {'KEEP' if row.get('keep') else 'DELETE'}  \n"
                f"{row.get('rationale', '')}"
            )


# ---------------------------------------------------------------------------
# Shell
# ---------------------------------------------------------------------------


def main() -> None:
    st.title("Antar")
    st.caption(
        "A causal revenue-recovery controller for Indian recurring payments. "
        "It decides *whether* to act, not just *how*."
    )

    ledgers = available_ledgers()
    with st.sidebar:
        st.header("Data")
        if not ledgers:
            st.error(
                "No ledger found in `artifacts/`.\n\n"
                "Run `python tasks.py simulate` to produce one."
            )
            chosen = None
            scenario = "base"
        else:
            chosen = st.selectbox("Ledger", ledgers, format_func=lambda p: p.name)
            scenario = chosen.stem.removeprefix("batch_")
        st.divider()
        view = st.radio(
            "View",
            ["Batch overview", "Decision trace", "Shadow prices"],
            index=1,
        )
        st.divider()
        st.caption(
            "Nothing in this console recomputes a decision. It reads the "
            "hash-chained ledger and the evaluation artifacts, so what you see is "
            "what was recorded."
        )

    if view == "Shadow prices":
        view_shadow_prices(scenario)
        return

    if chosen is None:
        st.warning("Select a ledger to continue.")
        return

    ledger = open_ledger(str(chosen))
    if view == "Batch overview":
        view_batch_overview(ledger, scenario)
    else:
        view_trace_explorer(ledger)


main()
